Controllers/mSlideController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Jarchim.da;
using Jarchim.Models;
using Jarchim.Models.database;
using System.IO;

namespace Jarchim.Controllers
{
    public class mSlideController : Controller
    {
        // GET: mSlide
        daLogin l = new daLogin();
        daSlide s = new daSlide();
        JarchimDb Db = new JarchimDb();
        // GET: mSlide
        public int fUserControl()
        {
            if ((Session["user_email"] != null) && (Session["user_pass"] != null))
            {
                ViewBag.username = Session["user_email"];
                return 1;
            }
            else
            {
                return 0;
            }
        }

        public ActionResult Index()
        {
            if (fUserControl() == 0)
            {
                ViewBag.Message = "شما وارد سایت نشده اید...";
                return RedirectToAction("LoginForm", "Login");
            }
            List<mSlider> aSlider = new List<mSlider>();
            aSlider = s.fSliderList();
            ViewBag.title = "فهرست تصاویر";
            return View(aSlider);

        }

        [HttpGet]
        public ActionResult Create()
        {
            if (fUserControl() == 0)
            {
                ViewBag.Message = "شما وارد سایت نشده اید...";
                return RedirectToAction("LoginForm", "Login");
            }
            mSlider vSlider = new mSlider();
            ViewBag.title = "تصویر جدید ";
            return View(vSlider);
        }

        [HttpPost, ValidateInput(false)]
        public ActionResult Create(mSlider pSlider)
        {
            if (fUserControl() == 0)
            {
                ViewBag.Message = "شما وارد سایت نشده اید...";
                return RedirectToAction("LoginForm", "Login");
            }
            ViewBag.title = "تصویر جدید ";
            if (!(ModelState.IsValid))
            {
                ViewBag.error = "خطا در  اطلاعات ورودی !";
                return View(pSlider);

            }
            else
            {
                if (pSlider.img_file != null && pSlider.img_file.ContentLength > 0)
                {
                    if (pSlider.img_file.ContentLength < 10485760)
                    {
                        Random rnd = new Random();
                        string img = rnd.Next().ToString() + ".jpg";
                        string Path = System.IO.Path.Combine(Server.MapPath("~/images/slider/"));
                        pSlider.img_file.SaveAs(Path + img);
                        using (MemoryStream ms = new MemoryStream())
                        {
                            pSlider.img_file.InputStream.CopyTo(ms);
                            byte[] array = ms.GetBuffer();
                            pSlider.slider_img = img;
                        }
                    }
                    else
                    {
                        ViewBag.error = "حد اکثر اندازه فایل را رعایت نکرده اید !";
                        return View(pSlider);
                    }
                }
                else
                {
                    ViewBag.error = "فایلی جهت آپلود انتخاب نشده است ";
                    return View(pSlider);
                }
                if (s.InsertSlider(pSlider))
                {
                    return RedirectToAction("index");
                }
                ViewBag.error = "خطا در انجام عملیات درج ! ";
            }
            return View(pSlider);
        }

        [HttpGet]
        public ActionResult Edit(int pId)
        {

            if (fUserControl() == 0)
            {
                ViewBag.Message = "شما وارد سایت نشده اید...";
                return RedirectToAction("LoginForm", "Login");
            }
            ViewBag.title = "ویرایش تصویر";
            mSlider vSlider = new mSlider();
            vSlider.slider_id = pId;
            vSlider = s.fGetSlider(vSlider);
            return View(vSlider);
        }

        [HttpPost, ValidateInput(false)]
        public ActionResult Edit(mSlider pSlider)
        {
            if (fUserControl() == 0)
            {
                ViewBag.Message = "شما وارد سایت نشده اید...";
                return RedirectToAction("LoginForm", "Login");
            }
            ViewBag.title = "ویرایش فایل";
            if (!(ModelState.IsValid))
            {
                ViewBag.error = "خطا در  اطلاعات ورودی !";
                return View(pSlider);

            }
            else
            {
                if (pSlider.img_file != null && pSlider.img_file.ContentLength > 0)
                {
                    if (pSlider.img_file.ContentLength < 10485760)
                    {
                        Random rnd = new Random();
                        string img = rnd.Next().ToString() + ".jpg";
                        string Path = System.IO.Path.Combine(Server.MapPath("~/images/slider/"));
                        pSlider.img_file.SaveAs(Path + img);
                        using (MemoryStream ms = new MemoryStream())
                        {
                            pSlider.img_file.InputStream.CopyTo(ms);
                            byte[] array = ms.GetBuffer();
                            pSlider.slider_img = img;
                        }
                    }
                    else
                    {
                        ViewBag.error = "حد اکثر اندازه فایل را رعایت نکرده اید !";
                        return View(pSlider);
                    }
                }
                if (s.fUpdateSlider(pSlider))
                {
                    return RedirectToAction("index");
                }
                ViewBag.error = "خطا در انجام عملیات ویرایش ! ";
            }
            return View(pSlider);
        }

        public ActionResult RemoveSlider(int pId)
        {

            if (fUserControl() == 0)
            {
                ViewBag.Message = "شما وارد سایت نشده اید...";
                return RedirectToAction("Login", "LoginForm");
            }
            mSlider vSlider = new mSlider();
            if (s.fDeleteSlider(pId))
            {
                return Json(pId, JsonRequestBehavior.AllowGet);
            }
            else
            {
                return Json(pId, JsonRequestBehavior.AllowGet);
            }
        }
    }
}

Views/mSlide/Create.cshtml
@model Jarchim.Models.mSlider
@{
    Jarchim.Models.database.JarchimDb JarchimDb = new Jarchim.Models.database.JarchimDb();
    Layout = "~/Views/Shared/_MLayout.cshtml";
}
<section class="content-header">
 <h1>
  اسلاید جدید
 </h1>
</section>
<!-- Content Header (Page header) -->
@using (Html.BeginForm("Create", "mSlide", FormMethod.Post, new { @enctype = "multipart/form-data", @class = "form-horizontal" } ))
{
    if (ViewBag.error != null)
    {
  <div class="col-md-8 form-group" style="margin-top:30px;margin-right:3px;">
   <div class="alert alert-dismissable alert-danger">
    @ViewBag.error
   </div>
  </div>
 }
 <!-- Main content -->
 <section class="content">
  <div class="row">
   <!-- right column -->
   <div class="col-md-8">
    <!-- Horizontal Form -->
    <div class="box box-info">
     <!-- form start -->
     <form class="form-horizontal">
      <div class="box-body">
       <input type="hidden" id="slider_id" value="@Model.slider_id" />
       <div class="form-group">
        <label class="col-sm-3 control-label" for="img_file">تصویر(1279*1920):</label>
        <div class="col-sm-9">
         <input type="file" name="img_file" id="" value="" />
        </div>
       </div>
       <div class="form-group">
        <label class="col-sm-3 control-label" for="slider_href"> نشانی / مقصد :</label>
        <div class="col-sm-9">
         @Html.TextBoxFor(model => model.slider_link, new { @placeholder = "نشانی / مقصد", @class = "form-control force" })
        </div>
       </div>
      </div>
      <!-- /.box-body -->
      <div class="box-footer">
       <button type="submit" class="btn btn-info pull-right sub_validation">ثبت</button>
      </div>
      <!-- /.box-footer -->
     </form>
    </div>
    <!-- /.box -->
   </div>
   <!--/.col (right) -->
  </div>
  <!-- /.row -->
 </section>
        <!-- /.content -->
}

Views/mSlide/Edit.cshtml
@model Jarchim.Models.mSlider
@{
    Jarchim.Models.database.JarchimDb JarchimDb = new Jarchim.Models.database.JarchimDb();
    Layout = "~/Views/Shared/_MLayout.cshtml";
}
<section class="content-header">
 <h1>
  ویرایش اسلاید
 </h1>
</section>
<!-- Content Header (Page header) -->
@using (Html.BeginForm("Edit", "mSlide", FormMethod.Post, new { @enctype = "multipart/form-data", @class = "form-horizontal" }))
{
    if (ViewBag.error != null)
    {
  <div class="col-md-8 form-group" style="margin-top:30px;margin-right:3px;">
   <div class="alert alert-dismissable alert-danger">
    @ViewBag.error
   </div>
  </div>
 }
 <!-- Main content -->
 <section class="content">
  <div class="row">
   <!-- right column -->
   <div class="col-md-8">
    <!-- Horizontal Form -->
    <div class="box box-info">
     <!-- form start -->
     <form class="form-horizontal">
      <div class="box-body">
          @Html.TextBoxFor(model => model.slider_id, new { @type = "hidden" })
          <div class="form-group">
              <input type="hidden" name="slider_img" id="slider_img" value="@Model.slider_img" />
              <label class="col-sm-3 control-label" for="img_file">تصویر(1279*1920):</label>
              <div class="col-sm-3">
                  <img src="~/images/slider/@Model.slider_img" width="70" height="70" />
              </div>
              <div class="col-sm-6">
                  <input type="file" name="img_file" id="" value="@Model.slider_img" />
              </div>
          </div>
       <div class="form-group">
        <label class="col-sm-3 control-label" for="slider_href"> نشانی / مقصد :</label>
        <div class="col-sm-9">
         @Html.TextBoxFor(model => model.slider_link, new { @placeholder = "نشانی / مقصد", @class = "form-control force" })
        </div>
       </div>
      </div>
      <!-- /.box-body -->
      <div class="box-footer">
       <button type="submit" class="btn btn-info pull-right sub_validation">ویرایش</button>
      </div>
      <!-- /.box-footer -->
     </form>
    </div>
    <!-- /.box -->
   </div>
   <!--/.col (right) -->
  </div>
  <!-- /.row -->
 </section>
        <!-- /.content -->
}

Views/mSlide/Index.cshtml
@model IEnumerable<Jarchim.Models.mSlider>
@{
 ViewBag.Title = "فهرست اسلاید ها";
 Layout = "~/Views/Shared/_MLayout.cshtml";
}
<!-- Content Header (Page header) -->
<section class="content-header" style="margin-left:15px;">
 <div class="row my-rows text-left">
  <button class="btn btn-danger delete" type="submit">
   <span class="fa fa-trash"></span>
   حذف
  </button>
  @Html.ActionLink("جدید", "Create", "mSlide", "", new { @class = "btn btn-success" })
 </div>
</section>

<!-- Main content -->
<section class="content">
 <div class="row">
  <div class="col-xs-12">
   <!-- /.box -->
   <div class="box">
    <!-- /.box-header -->
    <div class="box-body">
     <table class="table table-bordered table-striped">
      <thead>
       <tr>
        <th>تصویر </th>
        <th>نشانی / مقصد </th>
        <th>ویرایش</th>
        <th>حذف</th>
       </tr>
      </thead>
      <tbody>
       @foreach (var item in Model)
       {
        <tr id="@item.slider_id">
         <td>
          <img width="70" height="70" src="~/images/slider/@item.slider_img" />
         </td>
         <td>@item.slider_link</td>
         <td><a href="~/mSlide/Edit?pId=@item.slider_id" class="btn btn-info icon-preview"><i data-toggle="tooltip" data-placement="right" data-original-title="ویرایش" class="fa fa-pencil"> </i></a></td>
         <td><input value="@item.slider_id" name="radioSelect" type="radio"></td>
        </tr>
       }
      </tbody>
     </table>
    </div>
    <!-- /.box-body -->
   </div>
   <!-- /.box -->
  </div>
  <!-- /.col -->
 </div>
 <!-- /.row -->
</section>
<!-- /.content -->

@section crudScript{
 <script>
                $('.delete').click(function (event) {
                    url = get_current_url();
                    event.preventDefault();
                    var r = confirm("آیا از حذف رکورد اطمینان دارید؟");
                    if (r == true) {
                        var pIds = $('input[name="radioSelect"]:radio:checked').val();
                        $.ajax({
                         url: url + '/RemoveSlider',
                            dataType: "json",
                            data: { "pId": pIds },
                            type: "POST",
                            async: "true",
                            cache: false,
                            beforeSend: function () {
                            },
                            success: function (data) {
                                $("#" + pIds).remove()
                            }
                        });
                    }
                });
                function get_current_url() {
                    project = window.location.pathname.split('/');
                    url = window.location.protocol + '//' + window.location.host + '/' + project[1];
                    return url;
                }
 </script>
}