Models/mAdImg.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace Jarchim.Models
{
    public class mAdImg
    {
        public long img_id { get; set; }
        public long ad_id { get; set; }
        public Nullable<int> ad_cat { get; set; }
        public Nullable<int> ad_city { get; set; }
        public string ad_img { get; set; }
        public string ad_img_title { get; set; }
        public HttpPostedFileBase img_file { get; set; }
  public string ad_img_alt { get; set; }
 }
}

Controllers/mAdImgController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Jarchim.da;
using Jarchim.Models;
using Jarchim.Models.database;
using System.IO;
namespace Jarchim.Controllers
{
    public class mAdImgController : Controller
    {
        daLogin l = new daLogin();
        daAdImg n = new daAdImg();
        JarchimDb Db = new JarchimDb();
        static int pGet = 15;
        static int pSkip = 0;
        // GET: mNews
        public int fUserControl()
        {
            if ((Session["user_email"] != null) && (Session["user_pass"] != null))
            {
                ViewBag.username = Session["user_email"];
                return 1;
            }
            else
            {
                return 0;
            }
        }
        public ActionResult Index(mAdImg pAdImg)
        {
            if (fUserControl() == 0)
            {
                ViewBag.Message = "شما وارد سایت نشده اید...";
                return RedirectToAction("LoginForm", "Login");

            }
            if (pAdImg.ad_id > 0)
            {
                ViewBag.IsSearch = "On";
            }
            List<mAdImg> aAdImg = new List<mAdImg>();
            aAdImg = n.fAdImgList(pGet, pSkip,pAdImg);
            ViewBag.title = "فهرست تصاویر";
            if (pAdImg.ad_id > 0)
            {
                return PartialView("_Index",aAdImg);
            }
            else
            {
                return View(aAdImg);

            }
        }

        [HttpGet]
        public ActionResult Create()
        {
            if (fUserControl() == 0)
            {
                ViewBag.Message = "شما وارد سایت نشده اید...";
                return RedirectToAction("LoginForm", "Login");

            }
            mAdImg vAdImg = new mAdImg();
            ViewBag.title = "تصویر جدید ";
            return View(vAdImg);
        }

        [HttpPost, ValidateInput(false)]
        public ActionResult Create(mAdImg pAdImg)
        {
            if (fUserControl() == 0)
            {
                ViewBag.Message = "شما وارد سایت نشده اید...";
                return RedirectToAction("LoginForm", "Login");

            }
            ViewBag.title = "تصویر جدید ";
            if (!(ModelState.IsValid))
            {
                ViewBag.error = "خطا در  اطلاعات ورودی !";
                return View(pAdImg);

            }
            else
            {
                if (pAdImg.img_file != null && pAdImg.img_file.ContentLength > 0)
                {
                    if (pAdImg.img_file.ContentLength < 10485760)
                    {
                        Random rnd = new Random();
                        string img = rnd.Next().ToString() + ".jpg";
                        string Path = System.IO.Path.Combine(Server.MapPath("~/images/ads/"));
                        pAdImg.img_file.SaveAs(Path + img);
                        using (MemoryStream ms = new MemoryStream())
                        {
                            pAdImg.img_file.InputStream.CopyTo(ms);
                            byte[] array = ms.GetBuffer();
                            pAdImg.ad_img = img;
                        }
                    }
                    else
                    {
                        ViewBag.error = "حد اکثر اندازه فایل را رعایت نکرده اید !";
                        return View(pAdImg);
                    }
                }
                else
                {
                    ViewBag.error = "فایلی جهت آپلود انتخاب نشده است ";
                    return View(pAdImg);
                }
                if (n.InsertAdImg(pAdImg))
                {
                    return RedirectToAction("index");
                }
                ViewBag.error = "خطا در انجام عملیات درج ! ";
            }
            return View(pAdImg);
        }

        [HttpGet]
        public ActionResult Edit(int pId)
        {

            if (fUserControl() == 0)
            {
                ViewBag.Message = "شما وارد سایت نشده اید...";
                return RedirectToAction("LoginForm", "Login");
            }
            ViewBag.title = "ویرایش تصویر";
            mAdImg vAdImg = new mAdImg();
            vAdImg.img_id = pId;
            vAdImg = n.fGetAdImg(vAdImg);
            return View(vAdImg);
        }

        [HttpPost, ValidateInput(false)]
        public ActionResult Edit(mAdImg pAdImg)
        {
            if (fUserControl() == 0)
            {
                ViewBag.Message = "شما وارد سایت نشده اید...";
                return RedirectToAction("LoginForm", "Login");
            }
            ViewBag.title = "ویرایش تصویر";
            if (!(ModelState.IsValid))
            {
                ViewBag.error = "خطا در  اطلاعات ورودی !";
                return View(pAdImg);

            }
            else
            {
                if (pAdImg.img_file != null && pAdImg.img_file.ContentLength > 0)
                {
                    if (pAdImg.img_file.ContentLength < 10485760)
                    {
                        Random rnd = new Random();
                        string img = rnd.Next().ToString() + ".jpg";
                        string Path = System.IO.Path.Combine(Server.MapPath("~/images/ads/"));
                        pAdImg.img_file.SaveAs(Path + img);
                        using (MemoryStream ms = new MemoryStream())
                        {
                            pAdImg.img_file.InputStream.CopyTo(ms);
                            byte[] array = ms.GetBuffer();
                            pAdImg.ad_img = img;
                        }
                    }
                    else
                    {
                        ViewBag.error = "حد اکثر اندازه فایل را رعایت نکرده اید !";
                        return View(pAdImg);
                    }
                }
                if (n.fUpdateAdImg(pAdImg))
                {
                    return RedirectToAction("index");
                }
                ViewBag.error = "خطا در انجام عملیات ویرایش ! ";
            }
            return View(pAdImg);
        }

        public ActionResult RemoveAdImg(int pId)
        {

            if (fUserControl() == 0)
            {
                ViewBag.Message = "شما وارد سایت نشده اید...";
                return RedirectToAction("Login", "LoginForm");
            }
            mAdImg vAdImg = new mAdImg();
            if (n.fDeleteAdImg(pId))
            {
                return Json(pId, JsonRequestBehavior.AllowGet);
            }
            else
            {
                return Json(pId, JsonRequestBehavior.AllowGet);
            }
        }
        public ActionResult fGetPage(int pPageNum, string pAction)
        {
            pSkip = (pPageNum - 1) * pGet;
            return RedirectToAction(pAction);
        }
    }
}

Views/mAdImg/Create.cshtml
@model Jarchim.Models.mAdImg
@{
    Jarchim.Models.database.JarchimDb JarchimDb = new Jarchim.Models.database.JarchimDb();
    Layout = "~/Views/Shared/_MLayout.cshtml";
}
<section class="content-header">
 <h1>
     تصویر جدید
 </h1>
</section>
<!-- Content Header (Page header) -->
@using (Html.BeginForm("Create", "mAdImg", FormMethod.Post, new { @enctype = "multipart/form-data", @class = "form-horizontal" }))
{
 if (ViewBag.error != null)
 {
  <div class="col-md-8 form-group" style="margin-top:30px;margin-right:3px;">
   <div class="alert alert-dismissable alert-danger">
    @ViewBag.error
   </div>
  </div>
 }
<!-- Main content -->
    <section class="content">
        <div class="row">
            <!-- right column -->
            <div class="col-md-12">
                <!-- Horizontal Form -->
                <div class="box box-info">
                    <!-- form start -->
                    <form class="form-horizontal">
                        <div class="box-body">
                            <div class="form-group">
                                <input type="hidden" name="ad_img" id="ad_img" value="@Model.ad_img" />
                                <label class="col-sm-2 control-label" for="img_file">تصویر:</label>
                                <div class="col-sm-2">
                                    <img src="~/images/ads/@Model.ad_img" width="70" height="70" />
                                </div>
                                <div class="col-sm-6">
                                    <input type="file" name="img_file" id="" value="@Model.ad_img" />
                                </div>
                            </div>
                            <div class="form-group">
                                <label class="col-sm-2 control-label" for="ad_img_title">عنوان : </label>
                                <div class="col-sm-6">
                                    @Html.TextBoxFor(model => model.ad_img_title, new { @placeholder = "عنوان", @class = "form-control force" })
                                </div>
                            </div>
                            <div class="form-group">
                                <label class="col-sm-2 control-label" for="ad_id">آگهی :</label>
                                <div class="col-sm-4">
                                    @{
                                        var qAd = from n in JarchimDb.tbl_ad
                                                  select n;
                                    }
                                    <select class="form-control select2" id="ad_id" name="ad_id">
                                        <option value="0">همه</option>
                                        @foreach (var vAd in qAd)
                                        {
                                            <option value="@vAd.ad_id">
                                                @vAd.ad_name
                                            </option>
                                        }

                                    </select>
                                </div>
                            </div>
                        </div>
                        <!-- /.box-body -->
                        <div class="box-footer">
                            <button type="submit" class="btn btn-info pull-right sub_validation">ثبت</button>
                        </div>
                        <!-- /.box-footer -->
                    </form>
                </div>
                <!-- /.box -->
            </div>
            <!--/.col (right) -->
        </div>
        <!-- /.row -->
    </section>
        <!-- /.content -->
}

Views/mAdImg/Edit.cshtml
@model Jarchim.Models.mAdImg
@{
    Jarchim.Models.database.JarchimDb JarchimDb = new Jarchim.Models.database.JarchimDb();
    Layout = "~/Views/Shared/_MLayout.cshtml";
}
<section class="content-header">
 <h1>
ویرایش تصویر
  </h1>
</section>
<!-- Content Header (Page header) -->
@using (Html.BeginForm("Edit", "mAdImg", FormMethod.Post, new { @enctype = "multipart/form-data", @class = "form-horizontal" }))
{
 if (ViewBag.error != null)
 {
  <div class="col-md-8 form-group" style="margin-top:30px;margin-right:3px;">
   <div class="alert alert-dismissable alert-danger">
    @ViewBag.error
   </div>
  </div>
 }
 <!-- Main content -->
 <section class="content">
  <div class="row">
   <!-- right column -->
   <div class="col-md-12">
    <!-- Horizontal Form -->
    <div class="box box-info">
     <!-- form start -->
     <form class="form-horizontal">
      <div class="box-body">
          @Html.TextBoxFor(model => model.ad_id, new { @type = "hidden" })
          @Html.TextBoxFor(model => model.img_id, new { @type = "hidden" })
          <div class="form-group">
              <input type="hidden" name="ad_img" id="ad_img" value="@Model.ad_img" />
              <label class="col-sm-2 control-label" for="img_file">تصویر:</label>
              <div class="col-sm-2">
                  <img src="~/images/ads/@Model.ad_img" width="70" height="70" />
              </div>
              <div class="col-sm-6">
                  <input type="file" name="img_file" id="" value="@Model.ad_img" />
              </div>
          </div>
       <div class="form-group">
        <label class="col-sm-2 control-label" for="ad_img_title">عنوان : </label>
        <div class="col-sm-6">
         @Html.TextBoxFor(model => model.ad_img_title, new { @placeholder = "عنوان", @class = "form-control force" })
        </div>
       </div>
          @*<div class="form-group">
              <label class="col-sm-2 control-label" for="ad_id">آگهی :</label>
              <div class="col-sm-4">
                  @{
                      var qAd = from n in JarchimDb.tbl_ad
                                select n;
                  }
                  <select class="form-control select2" id="ad_id" name="ad_id">
                      <option value="0">همه</option>
                      @foreach (var vAd in qAd)
                      {
                          <option @if (vAd.ad_id == Model.img_id) {@:selected
                                  } value="@vAd.ad_id">
                      @vAd.ad_name
                          </option>
                      }

                  </select>
              </div>
          </div>*@

      </div>
      <!-- /.box-body -->
      <div class="box-footer">
       <button type="submit" class="btn btn-info pull-right sub_validation">ویرایش</button>
      </div>
      <!-- /.box-footer -->
     </form>
    </div>
    <!-- /.box -->
   </div>
   <!--/.col (right) -->
  </div>
  <!-- /.row -->
 </section>
        <!-- /.content -->
}

Views/mAdImg/Index.cshtml
@model IEnumerable<Jarchim.Models.mAdImg>
@{
    ViewBag.Title = "فهرست تصاویر";
    Layout = "~/Views/Shared/_MLayout.cshtml";
    Jarchim.Models.database.JarchimDb JarchimDb = new Jarchim.Models.database.JarchimDb();
    Jarchim.da.daCategory c = new Jarchim.da.daCategory();}
<!-- Content Header (Page header) -->
<section class="content-header" style="margin-left:15px;">
    <div class="row my-rows text-left">
        <button class="btn btn-danger delete" type="submit">
            <span class="fa fa-trash"></span>
            حذف
        </button>
        @Html.ActionLink("جدید", "Create", "mAdImg", "", new { @class = "btn btn-success" })
    </div>
</section>
<div class="col col-md-12" style="margin-top:30px;">
    <div class="col col-md-3 form-group">
        <label class="col-sm-4 control-label" for="ad_city"> شهر :</label>
        <div class="col-sm-8">
            @{
                var qCity = from n in JarchimDb.tbl_city
                            select n;
            }
            <select class="form-control select2" id="ad_city" name="ad_city">
                <option value="0">همه</option>
                @foreach (var vCity in qCity)
            {
                    <option value="@vCity.city_id">
                        @vCity.city_title
                    </option>
                }

            </select>

        </div>
    </div>
    <div class="col col-md-4 form-group">
        <label class="col-sm-5 control-label" for="ad_cat"> دسته بندی :</label>
        <div class="col-sm-7">
            @{
                var qCat = from n in JarchimDb.tbl_category
                           select n;
            }
            <select class="form-control select2" id="ad_cat" name="ad_cat">
                <option value="0">همه</option>
                @foreach (var vCat in qCat)
            {
                    <option value="@vCat.cat_id">
                        @vCat.cat_title
                    </option>
                }

            </select>

        </div>
    </div>
    <div class="col col-md-4 form-group">
        <label class="col-sm-3 control-label" for="ad_id">آگهی :</label>
        <div class="col-sm-9">
            @{
                var qAd = from n in JarchimDb.tbl_ad
                           select n;
            }
            <select class="form-control select2" id="ad_id" name="ad_id">
                <option value="0">همه</option>
                @foreach (var vAd in qAd)
            {
                    <option value="@vAd.ad_id">
                        @vAd.ad_name
                    </option>
                }

            </select>
        </div>
    </div>
    <div class="col col-md-1 form-group">
        <button class="btn btn-success search_ad" type="submit">
            جستجو
        </button>
    </div>
</div>
<div id="search-ad-result">
    @Html.Partial("_Index")
</div>
@section crudScript{
    <script>

        function get_current_url() {
            project = window.location.pathname.split('/');
            url = window.location.protocol + '//' + window.location.host + '/' + project[1];
            return url;
        }
        $('.delete').click(function (event) {
            url = get_current_url();
            event.preventDefault();
            var r = confirm("آیا از حذف رکورد اطمینان دارید؟");
            if (r == true) {
                var pIds = $('input[name="radioSelect"]:radio:checked').val();
                alert(pIds)
                alert()
                $.ajax({
                    url: url + '/RemoveAdImg',
                    dataType: "json",
                    data: { "pId": pIds },
                    type: "POST",
                    async: "true",
                    cache: false,
                    beforeSend: function () {
                    },
                    success: function (data) {
                        $("#" + pIds).remove()
                    }
                });
            }
        });
        function fGetUrl() {
            url = window.location.protocol + '//' + window.location.host + '/'
            return url;
        }
        vUrl = fGetUrl();
        $("body").on("click", ".search_ad", function () {
            vAdCity = $("#ad_city").val()
            vAdCat = $("#ad_cat").val()
            vAdId = $("#ad_id").val()
            if (vAdCat == 0 || vAdCity == 0 || vAdId == 0) {
                alert("برای جستجو انتخاب هر سه آیتم الزامی است")
                return 0;
            }
            pData = { ad_city: vAdCity, ad_cat: vAdCat, ad_id: vAdId }
            $.ajax({
                url: vUrl + "mAdImg" + "/" + "Index",
                type: "POST",
                contentType: 'application/json',
                data: JSON.stringify(pData),
                cache: false,
                async: false,
                beforeSend: function () {
                    $('span.psd-loader').css('display', 'block')
                },
                success: function (data) {
                    $('span.psd-loader').css('display', 'none')
                    vPartial = data
                },
                error: function (errormessage) {
                    alert(errormessage)
                    $('span.psd-loader').css('display', 'none')
                }
            });
            $("#search-ad-result").html(vPartial)

        });
    </script>
}

Views/mAdImg/_Index.cshtml
@model IEnumerable<Jarchim.Models.mAdImg>
@{
    ViewBag.Title = "فهرست تصاویر";
    Jarchim.Models.database.JarchimDb JarchimDb = new Jarchim.Models.database.JarchimDb();
    Jarchim.da.daCategory c = new Jarchim.da.daCategory();}
<!-- Main content -->

<section class="content">
    <div class="row">
        <div class="col-xs-12">
            <!-- /.box -->
            <div class="box">
                <!-- /.box-header -->
                <div class="box-body">
                    <table class="table table-bordered table-striped">
                        <thead>
                            <tr>
                                <th>تصویر</th>
                                <th>عنوان</th>
                                <th>ویرایش</th>
                                <th>حذف</th>
                            </tr>
                        </thead>
                        <tbody>
                            @foreach (var item in Model)
                            {

                                <input type="hidden" id="ad_id" value="@item.ad_id" />
                                <input type="hidden" id="ad_cat" value="@item.ad_cat" />
                                <input type="hidden" id="ad_city" value="@item.ad_city" />

                                        <tr id="@item.img_id">
                                            <td>
                                                <img width="70" height="70" src="~/images/ads/@item.ad_img" />
                                            </td>
                                            <td>@Html.DisplayFor(modelItem => item.ad_img_title)</td>
                                            <td><a href="~/mAdImg/Edit?pId=@item.img_id" class="btn btn-info icon-preview"><i data-toggle="tooltip" data-placement="right" data-original-title="ویرایش" class="fa fa-pencil"> </i></a></td>
                                            <td><input value="@item.ad_id" name="radioSelect" type="radio"></td>
                                        </tr>
                            }
                        </tbody>
                    </table>

                    @{
                        decimal vCount = (from a in JarchimDb.tbl_img_ad
                                          select a).Count();
                        decimal vPage = vCount / 15;
                    }
                    <div class="col-12" dir="rtl">
                        <div class="pagination-wrap text-center">
                            <ul>
                                @if (c.IsDecimal(vPage))
                                {
                                    vPage++;
                                }
                                @for (int i = 1; i <= vPage; i++)
                                {
                                    <li><a href="~/mAdImg/fGetPage?pPageNum=@i&pAction=Index">@i</a></li>
                                }
                            </ul>
                        </div>
                    </div>

                </div>
                <!-- /.box-body -->
            </div>
            <!-- /.box -->
        </div>
        <!-- /.col -->
    </div>
    <!-- /.row -->
</section>
<!-- /.content -->