Models/mAd.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace Jarchim.Models
{
 public class mAd
 {
  public long ad_id { get; set; }
  public string ad_name { get; set; }
  public string ad_price { get; set; }
  public Nullable<long> copen_id { get; set; }
  public string ad_exp_one { get; set; }
  public Nullable<System.DateTime> ad_from_date { get; set; }
  public Nullable<System.DateTime> ad_to_date { get; set; }
  public string ad_from_date_str { get; set; }
  public string ad_to_time_str { get; set; }
  public string ad_from_time_str { get; set; }
  public string ad_to_date_str { get; set; }
  public Nullable<int> ad_visit { get; set; }
  public Nullable<int> ad_like { get; set; }
  public Nullable<int> ad_dislike { get; set; }
  public Nullable<int> user_id { get; set; }
  public Nullable<long> img_id { get; set; }
  public string ad_exp_two { get; set; }
  public string ad_exp_three { get; set; }
  public string ad_summery { get; set; }
  public string ad_img { get; set; }
  public string cat_name { get; set; }
  public string timer_string { get; set; }
  public Nullable<int> ad_buy_count { get; set; }
  public Nullable<int> ad_save_per { get; set; }
  public int ad_cat { get; set; }
  public Nullable<int> ad_city { get; set; }
  public Nullable<int> ad_top_id { get; set; }
  public Nullable<int> is_search { get; set; }
  public HttpPostedFileBase img_file { get; set; }
  public List<mAdImg> aAdImg { get; set; }
        public decimal rating_avg { get; set; }

    }
}

Controllers/mAdsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Jarchim.da;
using Jarchim.Models;
using Jarchim.Models.database;
using System.IO;
namespace Jarchim.Controllers
{
    public class mAdsController : Controller
    {
        // GET: mAds
        daLogin l = new daLogin();
        daAds n = new daAds();
        JarchimDb Db = new JarchimDb();
        static int pGet = 15;
        static int pSkip = 0;
        // GET: mNews
        public int fUserControl()
        {
            if ((Session["user_email"] != null) && (Session["user_pass"] != null))
            {
                ViewBag.username = Session["user_email"];
                return 1;
            }
            else
            {
                return 0;
            }
        }
        public ActionResult Index(mAd pAd)
        {
            if (fUserControl() == 0)
            {
                ViewBag.Message = "شما وارد سایت نشده اید...";
                return RedirectToAction("LoginForm", "Login");

            }
            if (pAd.ad_id > 0)
            {
                ViewBag.IsSearch = "On";
            }
            List<mAd> aAd = new List<mAd>();
            aAd = n.fAdList(pGet, pSkip, pAd);
            ViewBag.title = "فهرست آگهی ها";
            if (pAd.ad_cat > 0)
            {
                return PartialView("_Index", aAd);
            }
            else
            {
                return View(aAd);

            }
        }

        [HttpGet]
        public ActionResult Create()
        {
   DateTime vNowTime = DateTime.Now;
   
   ViewBag.vDefultDate = vNowTime.ToString();
   if (fUserControl() == 0)
            {
                ViewBag.Message = "شما وارد سایت نشده اید...";
                return RedirectToAction("LoginForm", "Login");

            }
            mAd vAds = new mAd();
            ViewBag.title = "آگهی جدید ";
            return View(vAds);
        }

        [HttpPost, ValidateInput(false)]
        public ActionResult Create(mAd pAds)
        {
   //pAds.ad_from_date.Value.Hour= DateTime.Now.Hour;
 
   DateTime vNowTime = DateTime.Now;
   DateTime dateWithRightTime1 = pAds.ad_to_date.Value;
   DateTime dateWithRightTime = dateWithRightTime1.Date.Add(vNowTime.TimeOfDay);
   pAds.ad_to_date = dateWithRightTime;
   if (fUserControl() == 0)
            {
                ViewBag.Message = "شما وارد سایت نشده اید...";
                return RedirectToAction("LoginForm", "Login");

            }
            ViewBag.title = "آگهی جدید ";
            if (!(ModelState.IsValid))
            {
                ViewBag.error = "خطا در  اطلاعات ورودی !";
                return View(pAds);

            }
            else
            {
                if (n.InsertAds(pAds))
                {
                    return RedirectToAction("index");
                }
                ViewBag.error = "خطا در انجام عملیات درج ! ";
            }
            return View(pAds);
        }

        [HttpGet]
        public ActionResult Edit(int pId)
        {

            if (fUserControl() == 0)
            {
                ViewBag.Message = "شما وارد سایت نشده اید...";
                return RedirectToAction("LoginForm", "Login");
            }
            ViewBag.title = "ویرایش آگهی";
            mAd vAds = new mAd();
            vAds.ad_id = pId;
            vAds = n.fGetmAds(vAds);
            return View(vAds);
        }

        [HttpPost, ValidateInput(false)]
        public ActionResult Edit(mAd pAds)
        {
   DateTime vNowTime = DateTime.Now;
   DateTime dateWithRightTime1 = pAds.ad_from_date.Value;
   DateTime dateWithRightTime = dateWithRightTime1.Date.Add(vNowTime.TimeOfDay);
   pAds.ad_from_date = dateWithRightTime;

   DateTime dateWithRightTime2 = pAds.ad_to_date.Value;
   DateTime dateWithRightTime3 = dateWithRightTime2.Date.Add(vNowTime.TimeOfDay);
   pAds.ad_to_date = dateWithRightTime3;
   if (fUserControl() == 0)
            {
                ViewBag.Message = "شما وارد سایت نشده اید...";
                return RedirectToAction("LoginForm", "Login");
            }
            ViewBag.title = "ویرایش آگهی";
            if (!(ModelState.IsValid))
            {
                ViewBag.error = "خطا در  اطلاعات ورودی !";
                return View(pAds);

            }
            else
            {
                if (n.fUpdateAds(pAds))
                {
                    return RedirectToAction("index");
                }
                ViewBag.error = "خطا در انجام عملیات ویرایش ! ";
            }
            return View(pAds);
        }

        public ActionResult RemoveAds(int pId)
        {

            if (fUserControl() == 0)
            {
                ViewBag.Message = "شما وارد سایت نشده اید...";
                return RedirectToAction("Login", "LoginForm");
            }
            mAd vNews = new mAd();
            if (n.fDeleteAds(pId))
            {
                return Json(pId, JsonRequestBehavior.AllowGet);
            }
            else
            {
                return Json(pId, JsonRequestBehavior.AllowGet);
            }
        }
        public ActionResult fGetPage(int pPageNum, string pAction)
        {
            pSkip = (pPageNum - 1) * pGet;
            return RedirectToAction(pAction);
        }
    }
}

Views/mAds/Create.cshtml
@model Jarchim.Models.mAd
@{
 Jarchim.Models.database.JarchimDb JarchimDb = new Jarchim.Models.database.JarchimDb();
 Layout = "~/Views/Shared/_MLayout.cshtml";
 
}
<link href="~/css/BootstrapJalaliDatePicker/bootstrap-datepicker.min.css" rel="stylesheet" />

<section class="content-header">
 <h1>
     آگهی  جدید
 </h1>
</section>
<!-- Content Header (Page header) -->
@using (Html.BeginForm("Create", "mAds", FormMethod.Post, new { @enctype = "multipart/form-data", @class = "form-horizontal" }))
{
 if (ViewBag.error != null)
 {
  <div class="col-md-8 form-group" style="margin-top:30px;margin-right:3px;">
   <div class="alert alert-dismissable alert-danger">
    @ViewBag.error
   </div>
  </div>
 }
<!-- Main content -->
 <section class="content">
  <div class="row">
   <!-- right column -->
   <div class="col-md-12">
    <!-- Horizontal Form -->
    <div class="box box-info">
     <!-- form start -->
        <form class="form-horizontal">
            <div class="box-body">
                @Html.TextBoxFor(model => model.ad_id, new { @type = "hidden" })

                <div class="form-group">
                    <label class="col-sm-2 control-label" for="ad_name">عنوان : </label>
                    <div class="col-sm-6">
                        @Html.TextBoxFor(model => model.ad_name, new { @placeholder = "عنوان", @class = "form-control force" })
                    </div>
                </div>
                <div class="form-group">
                    <label class="col-sm-2 control-label" for="ad_price">قیمت: </label>
                    <div class="col-sm-2">
                        @Html.TextBoxFor(model => model.ad_price, new { @placeholder = "قیمت", @class = "form-control force" })
                    </div>
                </div>
                <div class="form-group">
                    <label class="col-sm-2 control-label" for="ad_buy_count"> تعداد فروش :</label>
                    <div class="col-sm-1">
                        @Html.TextBoxFor(model => model.ad_buy_count, new { @placeholder = "تعداد فروش", @class = "form-control force" })
                    </div>
                </div>
                <div class="form-group">
                    <label class="col-sm-2 control-label" for="ad_from_date_str"> از تاریخ :</label>
                    <div class="col-sm-2">
                     @Html.EditorFor(model => model.ad_from_date, new { htmlAttributes = new { @class = "form-control", autocomplete = "off" , @Value = @ViewBag.vDefultDate } })
                    </div>
                </div>
                <div class="form-group">
                    <label class="col-sm-2 control-label" for="ad_to_date_str"> تا تاریخ :</label>
                    <div class="col-sm-2">
                     @Html.EditorFor(model => model.ad_to_date, new { htmlAttributes = new { @class = "form-control", autocomplete = "off" , @Value = @ViewBag.vDefultDate } })
                    </div>
                </div>
                <div class="form-group">
                    <label class="col-sm-2 control-label" for="ad_date"> دسته بندی :</label>
                    <div class="col-sm-3">
                        @{
                            var qCat = from n in JarchimDb.tbl_category
                                        select n;
                        }
                        <select class="form-control select2" id="ad_cat" name="ad_cat">
                            <option value="0">همه</option>
                            @foreach (var vCat in qCat)
                            {
                                <option value="@vCat.cat_id">
                                    @vCat.cat_title
                                </option>
                            }

                        </select>

                    </div>
                </div>
                <div class="form-group">
                    <label class="col-sm-2 control-label" for="ad_date"> شهر :</label>
                    <div class="col-sm-3">
                        @{ 
                            var qCity = from n in JarchimDb.tbl_city
                                        select n;
                        }
                        <select class="form-control select2" id="ad_city" name="ad_city">
                            <option value="0">همه</option>
                            @foreach (var vCity in qCity)
                            {
                                <option value="@vCity.city_id">
                                   @vCity.city_title
                                </option>
                            }
                           
                        </select>

                    </div>
                </div>
                <div class="form-group">
                    <label class="col-sm-2 control-label" for="ad_like"> Like :</label>
                    <div class="col-sm-1">
                        @Html.TextBoxFor(model => model.ad_like, new { @placeholder = "Like", @class = "form-control force" })
                    </div>
                </div>
                <div class="form-group">
                    <label class="col-sm-2 control-label" for="ad_dislike"> Dislike :</label>
                    <div class="col-sm-1">
                        @Html.TextBoxFor(model => model.ad_dislike, new { @placeholder = "Dis", @class = "form-control force" })
                    </div>
                </div>
                <div class="form-group">
                    <label class="col-sm-2 control-label" for="ad_visit">Visit :</label>
                    <div class="col-sm-1">
                        @Html.TextBoxFor(model => model.ad_visit, new { @placeholder = "Visit", @class = "form-control force" })
                    </div>
                </div>
                <div class="form-group">
                    <div class="box-body pad">
                        <label class="col-sm-2 control-label" for="ad_summery">خلاصه :</label>
                        <div class="col-sm-10">
                            <textarea id="ad_summery" name="ad_summery" rows="10" cols="70">@Model.ad_summery</textarea>
                        </div>
                    </div>
                </div>
                <div class="form-group">
                    <div class="box-body pad">
                        <label class="col-sm-2 control-label" for="ad_exp_one"> شرح 1 :</label>
                        <div class="col-sm-10">
                            <textarea id="ad_exp_one" name="ad_exp_one" rows="10" cols="70">@Model.ad_exp_one</textarea>
                        </div>
                    </div>
                </div>
                <div class="form-group">
                    <div class="box-body pad">
                        <label class="col-sm-2 control-label" for="ad_exp_two">2 شرح  :</label>
                        <div class="col-sm-10">
                            <textarea id="ad_exp_two" name="ad_exp_two" rows="10" cols="70">@Model.ad_exp_two</textarea>
                        </div>
                    </div>
                </div>
                <div class="form-group">
                    <div class="box-body pad">
                        <label class="col-sm-2 control-label" for="ad_exp_three">3 شرح  :</label>
                        <div class="col-sm-10">
                            <textarea id="ad_exp_three" name="ad_exp_three" rows="10" cols="70">@Model.ad_exp_three</textarea>
                        </div>
                    </div>
                </div>
            </div>
            <!-- /.box-body -->
            <div class="box-footer">
                <button type="submit" class="btn btn-info pull-right sub_validation">ثبت</button>
            </div>
            <!-- /.box-footer -->
        </form>
    </div>
    <!-- /.box -->
   </div>
   <!--/.col (right) -->
  </div>
  <!-- /.row -->
 </section>
        <!-- /.content -->
}


@section crudScript{
    <script src="~/panel/bower_components/jquery/dist/jquery.min.js"></script>
    <!-- Bootstrap 3.3.7 -->
    <script src="~/panel/bower_components/ckeditor/ckeditor.js"></script>
    <!-- Bootstrap WYSIHTML5 -->
    <!--<script src="../../plugins/bootstrap-wysihtml5/bootstrap3-wysihtml5.all.min.js"></script>-->
    <!-- TinyMCE Editor -->
    <script src="~/panel/bower_components/tinymce/tinymce.min.js"></script>
    <script>
    tinymce.init({
        selector: 'textarea#mytextarea',
        plugins : 'advlist autolink link lists preview table code pagebreak',
        menubar: false,
        language: 'fa',
        height: 300,
        relative_urls: false,
        toolbar: 'undo redo | removeformat preview code | fontsizeselect bullist numlist | alignleft aligncenter alignright alignjustify | bold italic | pagebreak table link',
    });
  $(function () {
    // Replace the <textarea id="editor1"> with a CKEditor
    // instance, using default configuration.
      CKEDITOR.replace('ad_summery')
    //bootstrap WYSIHTML5 - text editor
    $('.textarea').wysihtml5()
  })
  $(function () {
      // Replace the <textarea id="editor1"> with a CKEditor
      // instance, using default configuration.
      CKEDITOR.replace('ad_exp_one')
      //bootstrap WYSIHTML5 - text editor
      $('.textarea').wysihtml5()
  })
  $(function () {
      // Replace the <textarea id="editor1"> with a CKEditor
      // instance, using default configuration.
      CKEDITOR.replace('ad_exp_two')
      //bootstrap WYSIHTML5 - text editor
      $('.textarea').wysihtml5()
  })
  $(function () {
      // Replace the <textarea id="editor1"> with a CKEditor
      // instance, using default configuration.
      CKEDITOR.replace('ad_exp_three')
      //bootstrap WYSIHTML5 - text editor
      $('.textarea').wysihtml5()
  })
    </script>
    <script>
    kamaDatepicker('ad_from_date_str', { buttonsColor: "red" });
    kamaDatepicker('ad_to_date_str', { buttonsColor: "red" });

		var customOptions = {
			placeholder: "روز / ماه / سال"
			, twodigit: false
			, closeAfterSelect: false
			, nextButtonIcon: "fa fa-arrow-circle-right"
			, previousButtonIcon: "fa fa-arrow-circle-left"
			, buttonsColor: "blue"
			, forceFarsiDigits: true
			, markToday: true
			, markHolidays: true
			, highlightSelectedDay: true
			, sync: true
			, gotoToday: true
		}
		// for testing sync functionallity
		//$("#ad_from_date_str").val("1311/10/01");
    </script>
<script src="~/js/BootstrapJalaliDatePicker/bootstrap-datepicker.fa.min.js"></script>
<script src="~/js/BootstrapJalaliDatePicker/bootstrap-datepicker.min.js"></script>
<script type="text/javascript">
    $(document).ready(function() {
        $('input[type=datetime]').datepicker({ dateFormat: "yy/mm/dd", isRTL: true, showButtonPanel: true });
    });
</script>
}


@*<asp:BoundField DataField="PAStatusDate" DataFormatString="{0:dd-MM-yyyy HH:mm}" HeaderText="PA Status Date" HtmlEncode="False" />*@

Views/mAds/Edit.cshtml
@model Jarchim.Models.mAd
@{
    Jarchim.Models.database.JarchimDb JarchimDb = new Jarchim.Models.database.JarchimDb();
    Layout = "~/Views/Shared/_MLayout.cshtml";
}
<section class="content-header">
 <h1>
ویرایش آگهی
  </h1>
</section>
<!-- Content Header (Page header) -->
@using (Html.BeginForm("Edit", "mAds", FormMethod.Post, new { @enctype = "multipart/form-data", @class = "form-horizontal" }))
{
 if (ViewBag.error != null)
 {
  <div class="col-md-8 form-group" style="margin-top:30px;margin-right:3px;">
   <div class="alert alert-dismissable alert-danger">
    @ViewBag.error
   </div>
  </div>
 }
 <!-- Main content -->
 <section class="content">
  <div class="row">
   <!-- right column -->
   <div class="col-md-12">
    <!-- Horizontal Form -->
    <div class="box box-info">
     <!-- form start -->
     <form class="form-horizontal">
      <div class="box-body">
          @Html.TextBoxFor(model => model.ad_id, new { @type = "hidden" })

          <div class="form-group">
              <label class="col-sm-2 control-label" for="ad_name">عنوان : </label>
              <div class="col-sm-6">
                  @Html.TextBoxFor(model => model.ad_name, new { @placeholder = "عنوان", @class = "form-control force" })
              </div>
          </div>
          <div class="form-group">
              <label class="col-sm-2 control-label" for="ad_price">قیمت: </label>
              <div class="col-sm-2">
                  @Html.TextBoxFor(model => model.ad_price, new { @placeholder = "قیمت", @class = "form-control force" })
              </div>
          </div>
          <div class="form-group">
              <label class="col-sm-2 control-label" for="ad_buy_count"> تعداد فروش :</label>
              <div class="col-sm-1">
                  @Html.TextBoxFor(model => model.ad_buy_count, new { @placeholder = "تعداد فروش", @class = "form-control force" })
              </div>
          </div>
       <div class="form-group">
        <label class="col-sm-2 control-label" for="ad_from_date_str"> از تاریخ :</label>
        <div class="col-sm-2">
         @Html.EditorFor(model => model.ad_from_date, new { htmlAttributes = new { @class = "form-control", autocomplete = "off" } })
        </div>
       </div>
       <div class="form-group">
        <label class="col-sm-2 control-label" for="ad_to_date_str"> تا تاریخ :</label>
        <div class="col-sm-2">
         @Html.EditorFor(model => model.ad_to_date, new { htmlAttributes = new { @class = "form-control", autocomplete = "off" } })
        </div>
       </div>
          <div class="form-group">
              <label class="col-sm-2 control-label" for="ad_date"> دسته بندی :</label>
              <div class="col-sm-3">
                  @{
                      var qCat = from n in JarchimDb.tbl_category
                                 select n;
                  }
                  <select class="form-control select2" id="ad_cat" name="ad_cat">
                      <option  value="0">همه</option>
                      @foreach (var vCat in qCat)
                      {
                          <option @if (Model.ad_cat == vCat.cat_id) { @:selected
                                  } value="@vCat.cat_id">
                              @vCat.cat_title
                          </option>
                      }

                  </select>

              </div>
          </div>
          <div class="form-group">
              <label class="col-sm-2 control-label" for="ad_date"> شهر :</label>
              <div class="col-sm-3">
                  @{
                      var qCity = from n in JarchimDb.tbl_city
                                  select n;
                  }
                  <select class="form-control select2" id="ad_city" name="ad_city">
                      <option value="0">همه</option>
                      @foreach (var vCity in qCity)
                      {
                          <option @if (Model.ad_city == vCity.city_id) { @:selected
                                  } value="@vCity.city_id">
                              @vCity.city_title
                          </option>
                      }

                  </select>

              </div>
          </div>
          <div class="form-group">
              <label class="col-sm-2 control-label" for="ad_like"> Like :</label>
              <div class="col-sm-1">
                  @Html.TextBoxFor(model => model.ad_like, new { @placeholder = "Like", @class = "form-control force" })
              </div>
          </div>
          <div class="form-group">
              <label class="col-sm-2 control-label" for="ad_dislike"> Dislike :</label>
              <div class="col-sm-1">
                  @Html.TextBoxFor(model => model.ad_dislike, new { @placeholder = "Dis", @class = "form-control force" })
              </div>
          </div>
          <div class="form-group">
              <label class="col-sm-2 control-label" for="ad_visit">Visit :</label>
              <div class="col-sm-1">
                  @Html.TextBoxFor(model => model.ad_visit, new { @placeholder = "Visit", @class = "form-control force" })
              </div>
          </div>
          <div class="form-group">
              <div class="box-body pad">
                  <label class="col-sm-2 control-label" for="ad_summery">خلاصه :</label>
                  <div class="col-sm-10">
                      <textarea id="ad_summery" name="ad_summery" rows="10" cols="70">@Model.ad_summery</textarea>
                  </div>
              </div>
          </div>
          <div class="form-group">
              <div class="box-body pad">
                  <label class="col-sm-2 control-label" for="ad_exp_one"> شرح 1 :</label>
                  <div class="col-sm-10">
                      <textarea id="ad_exp_one" name="ad_exp_one" rows="10" cols="70">@Model.ad_exp_one</textarea>
                  </div>
              </div>
          </div>
          <div class="form-group">
              <div class="box-body pad">
                  <label class="col-sm-2 control-label" for="ad_exp_two">2 شرح  :</label>
                  <div class="col-sm-10">
                      <textarea id="ad_exp_two" name="ad_exp_two" rows="10" cols="70">@Model.ad_exp_two</textarea>
                  </div>
              </div>
          </div>
          <div class="form-group">
              <div class="box-body pad">
                  <label class="col-sm-2 control-label" for="ad_exp_three">3 شرح  :</label>
                  <div class="col-sm-10">
                      <textarea id="ad_exp_three" name="ad_exp_three" rows="10" cols="70">@Model.ad_exp_three</textarea>
                  </div>
              </div>
          </div>
      </div>
      <!-- /.box-body -->
      <div class="box-footer">
       <button type="submit" class="btn btn-info pull-right sub_validation">ویرایش</button>
      </div>
      <!-- /.box-footer -->
     </form>
    </div>
    <!-- /.box -->
   </div>
   <!--/.col (right) -->
  </div>
  <!-- /.row -->
 </section>
        <!-- /.content -->
}

@section crudScript{
  <script src="~/panel/bower_components/jquery/dist/jquery.min.js"></script>
<!-- Bootstrap 3.3.7 -->
<script src="~/panel/bower_components/ckeditor/ckeditor.js"></script>
<!-- Bootstrap WYSIHTML5 -->
<!--<script src="../../plugins/bootstrap-wysihtml5/bootstrap3-wysihtml5.all.min.js"></script>-->
<!-- TinyMCE Editor -->
<script src="~/panel/bower_components/tinymce/tinymce.min.js"></script>
<script>
    tinymce.init({
        selector: 'textarea#mytextarea',
        plugins : 'advlist autolink link lists preview table code pagebreak',
        menubar: false,
        language: 'fa',
        height: 300,
        relative_urls: false,
        toolbar: 'undo redo | removeformat preview code | fontsizeselect bullist numlist | alignleft aligncenter alignright alignjustify | bold italic | pagebreak table link',
    });
  $(function () {
    // Replace the <textarea id="editor1"> with a CKEditor
    // instance, using default configuration.
      CKEDITOR.replace('ad_summery')
    //bootstrap WYSIHTML5 - text editor
    $('.textarea').wysihtml5()
  })
  $(function () {
      // Replace the <textarea id="editor1"> with a CKEditor
      // instance, using default configuration.
      CKEDITOR.replace('ad_exp_one')
      //bootstrap WYSIHTML5 - text editor
      $('.textarea').wysihtml5()
  })
  $(function () {
      // Replace the <textarea id="editor1"> with a CKEditor
      // instance, using default configuration.
      CKEDITOR.replace('ad_exp_two')
      //bootstrap WYSIHTML5 - text editor
      $('.textarea').wysihtml5()
  })
  $(function () {
      // Replace the <textarea id="editor1"> with a CKEditor
      // instance, using default configuration.
      CKEDITOR.replace('ad_exp_three')
      //bootstrap WYSIHTML5 - text editor
      $('.textarea').wysihtml5()
  })
</script>
<script>
    kamaDatepicker('ad_from_date_str', { buttonsColor: "red" });
    kamaDatepicker('ad_to_date_str', { buttonsColor: "red" });

		var customOptions = {
			placeholder: "روز / ماه / سال"
			, twodigit: false
			, closeAfterSelect: false
			, nextButtonIcon: "fa fa-arrow-circle-right"
			, previousButtonIcon: "fa fa-arrow-circle-left"
			, buttonsColor: "blue"
			, forceFarsiDigits: true
			, markToday: true
			, markHolidays: true
			, highlightSelectedDay: true
			, sync: true
			, gotoToday: true
		}
		// for testing sync functionallity
		//$("#ad_from_date_str").val("1311/10/01");
</script>  
    }

Views/mAds/Index.cshtml
@model IEnumerable<Jarchim.Models.mAd>
@{
    ViewBag.Title = "فهرست آگهی ها";
    Layout = "~/Views/Shared/_MLayout.cshtml";
    Jarchim.Models.database.JarchimDb JarchimDb = new Jarchim.Models.database.JarchimDb();
    Jarchim.da.daCategory c = new Jarchim.da.daCategory();}
<!-- Content Header (Page header) -->
<section class="content-header" style="margin-left:15px;">
    <div class="row my-rows text-left">
        <button class="btn btn-danger delete" type="submit">
            <span class="fa fa-trash"></span>
            حذف
        </button>
        @Html.ActionLink("جدید", "Create", "mAds", "", new { @class = "btn btn-success" })
    </div>
</section>
<div class="col col-md-12" style="margin-top:30px;">
    <div class="col col-md-4 form-group">
        <label class="col-sm-5 control-label" for="ad_cat"> دسته بندی :</label>
        <div class="col-sm-7">
            @{
                var qCat = from n in JarchimDb.tbl_category
                           select n;
            }
            <select class="form-control select2" id="ad_cat" name="ad_cat">
                <option value="0">همه</option>
                @foreach (var vCat in qCat)
            {
                    <option value="@vCat.cat_id">
                        @vCat.cat_title
                    </option>
                }

            </select>

        </div>
    </div>
    <div class="col col-md-4 form-group">
    </div>
    <div class="col col-md-1 form-group">
        <button class="btn btn-success search_cat" type="submit">
            جستجو
        </button>
    </div>
</div>
<div id="search-cat-result">
    @Html.Partial("_Index")
</div>

@section crudScript{
    <script>
        $('.delete').click(function (event) {
            url = get_current_url();
            event.preventDefault();
            var r = confirm("آیا از حذف رکورد اطمینان دارید؟");
            if (r == true) {
                var pIds = $('input[name="radioSelect"]:radio:checked').val();
                $.ajax({
                    url: url + '/RemoveAds',
                    dataType: "json",
                    data: { "pId": pIds },
                    type: "POST",
                    async: "true",
                    cache: false,
                    beforeSend: function () {
                    },
                    success: function (data) {
                        $("#" + pIds).remove()
                    }
                });
            }
        });
        function get_current_url() {
            project = window.location.pathname.split('/');
            url = window.location.protocol + '//' + window.location.host + '/' + project[1];
            return url;
        }
    </script>
    <script>
        function fGetUrl() {
            url = window.location.protocol + '//' + window.location.host + '/'
            return url;
        }
        vUrl = fGetUrl();
        $("body").on("click", ".search_cat", function () {
            vAdCat = $("#ad_cat").val()
             pData = {ad_cat: vAdCat}
            $.ajax({
                url: vUrl + "mAds" + "/" + "Index",
                type: "POST",
                contentType: 'application/json',
                data: JSON.stringify(pData),
                cache: false,
                async: false,
                beforeSend: function () {
                    $('span.psd-loader').css('display', 'block')
                },
                success: function (data) {
                    $('span.psd-loader').css('display', 'none')
                    vPartial = data
                },
                error: function (errormessage) {
                    alert(errormessage)
                    $('span.psd-loader').css('display', 'none')
                }
            });
            $("#search-cat-result").html(vPartial)
        });
    </script>
}